services:
  reliability-lab:
    build: ./health
    container_name: reliability-lab
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: reliability-lab-py
      VERSION: 1.0.0
      PORT: 8080
      # Para simular falha no health-check, defina HEALTH_FAIL=true ao rodar o comando ou mude aqui
      HEALTH_FAIL: "${HEALTH_FAIL:-true}"
